
name: PyTest

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - name: Set Configurations
        run: |
          echo "tenant_id: \"${{ secrets.TENANT_ID }}\"" >> config.yml
          echo "azure_preview_subscription: \"${{ secrets.SUBSCRIPTION_ID }}\"" >> config.yml
          echo "aad_id: \"${{ secrets.AAD_ID }}\"" >> config.yml
          echo "aad_secret: \"${{ secrets.AAD_SECRET }}\"" >> config.yml
          echo "access_id: \"${{ secrets.ACCESS_ID }}\"" >> config.yml

      - name: TOX Run Unit Tests
        uses: ymyzk/run-tox-gh-actions@v0.1
        with: 
          tox-args: -e py37-unit

      - name: TOX Run Integration Tests
        uses: ymyzk/run-tox-gh-actions@v0.1
        with: 
          tox-args: -e py37-integration
