
name: PyTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7

      - name: TOX Run Unit Tests
        uses: ymyzk/run-tox-gh-actions@v0.1
        with: 
          tox-args: -e py37-unit

      - name: TOX Run Integration Tests
        uses: ymyzk/run-tox-gh-actions@v0.1
        env: # Or as an environment variable
          AAD_ID: ${{ secrets.AAD_ID }}
          AAD_SECRET: ${{ secrets.AAD_SECRET }}
          ACCESS_ID: ${{ secrets.ACCESS_ID }}
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
        with: 
          tox-args: -e py37-integration
